[project]
name = "assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic-ai[logfire]>=0.2.6",
    "pydantic>=2.11.4",
    "requests>=2.32.3",
]
